import {
  Card,
  Text,
  BlockStack,
  InlineStack,
  TextField,
  Select,
  Checkbox,
  Button,
  Badge,
  Tabs,
  Icon,
  Banner,
} from '@shopify/polaris';
import {
  ProductIcon,
  StarFilledIcon,
  MoneyIcon,
  ImageIcon,
} from '@shopify/polaris-icons';
import { useState } from 'react';

export interface ProductSEOConfig {
  // Title & Description Templates
  titleTemplate: string;
  descriptionTemplate: string;

  // Schema Settings
  enableProductSchema: boolean;
  includeReviews: boolean;
  includeOffers: boolean;
  includeBrand: boolean;
  includeAvailability: boolean;

  // Meta Tag Settings
  autoGenerateTitles: boolean;
  autoGenerateDescriptions: boolean;
  includePrice: boolean;
  includeCategories: boolean;

  // URL Settings
  urlStructure: 'simple' | 'category' | 'full-path';
  removeStopWords: boolean;
  lowercaseUrls: boolean;

  // Image SEO
  autoGenerateAltText: boolean;
  altTextTemplate: string;
  optimizeImageNames: boolean;

  // Reviews & Ratings
  showStarRatings: boolean;
  minimumReviewsForRating: number;

  // Inventory
  hideOutOfStock: boolean;
  showStockAvailability: boolean;
}

export interface ProductSEOPreview {
  title: string;
  description: string;
  url: string;
  price: number;
  currency: string;
  rating?: number;
  reviewCount?: number;
  availability: 'in_stock' | 'out_of_stock' | 'preorder';
  brand?: string;
  category?: string;
}

interface ProductSEOSettingsProps {
  config?: ProductSEOConfig;
  previewProduct?: ProductSEOPreview;
  onSave?: (config: ProductSEOConfig) => void;
  onPreview?: (productId: string) => ProductSEOPreview;
}

const DEFAULT_CONFIG: ProductSEOConfig = {
  titleTemplate: '{product_name} | {store_name}',
  descriptionTemplate: '{product_description}',
  enableProductSchema: true,
  includeReviews: true,
  includeOffers: true,
  includeBrand: true,
  includeAvailability: true,
  autoGenerateTitles: true,
  autoGenerateDescriptions: true,
  includePrice: true,
  includeCategories: true,
  urlStructure: 'simple',
  removeStopWords: false,
  lowercaseUrls: true,
  autoGenerateAltText: true,
  altTextTemplate: '{product_name} - {variant}',
  optimizeImageNames: true,
  showStarRatings: true,
  minimumReviewsForRating: 1,
  hideOutOfStock: false,
  showStockAvailability: true,
};

const SAMPLE_PRODUCT: ProductSEOPreview = {
  title: 'Premium Wireless Headphones',
  description: 'High-quality wireless headphones with noise cancellation and 30-hour battery life.',
  url: '/products/premium-wireless-headphones',
  price: 299.99,
  currency: 'USD',
  rating: 4.8,
  reviewCount: 234,
  availability: 'in_stock',
  brand: 'AudioPro',
  category: 'Electronics > Audio',
};

export default function ProductSEOSettings({
  config: initialConfig = DEFAULT_CONFIG,
  previewProduct = SAMPLE_PRODUCT,
  onSave,
  onPreview,
}: ProductSEOSettingsProps) {
  const [config, setConfig] = useState<ProductSEOConfig>(initialConfig);
  const [selectedTab, setSelectedTab] = useState(0);
  const [hasChanges, setHasChanges] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState(false);

  const tabs = [
    { id: 'meta', content: 'Meta Tags', panelID: 'meta-panel' },
    { id: 'schema', content: 'Schema Markup', panelID: 'schema-panel' },
    { id: 'urls', content: 'URLs', panelID: 'urls-panel' },
    { id: 'images', content: 'Images', panelID: 'images-panel' },
  ];

  const updateConfig = (updates: Partial<ProductSEOConfig>) => {
    setConfig((prev) => ({ ...prev, ...updates }));
    setHasChanges(true);
    setError(null);
    setSuccess(false);
  };

  const handleSave = async () => {
    if (!onSave) return;

    setIsSaving(true);
    setError(null);
    setSuccess(false);

    try {
      await onSave(config);
      setHasChanges(false);
      setSuccess(true);
      setTimeout(() => setSuccess(false), 3000);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to save settings. Please try again.');
    } finally {
      setIsSaving(false);
    }
  };

  // Generate preview based on templates
  const generatePreviewTitle = () => {
    return config.titleTemplate
      .replace('{product_name}', previewProduct.title)
      .replace('{price}', `$${previewProduct.price}`)
      .replace('{brand}', previewProduct.brand || '')
      .replace('{category}', previewProduct.category || '')
      .replace('{store_name}', 'Your Store');
  };

  const generatePreviewDescription = () => {
    return config.descriptionTemplate
      .replace('{product_description}', previewProduct.description)
      .replace('{product_name}', previewProduct.title)
      .replace('{price}', `$${previewProduct.price}`)
      .replace('{brand}', previewProduct.brand || '');
  };

  const generatePreviewUrl = () => {
    const productSlug = previewProduct.title.toLowerCase().replace(/\s+/g, '-');
    switch (config.urlStructure) {
      case 'simple':
        return `/products/${productSlug}`;
      case 'category':
        return `/products/${previewProduct.category?.split(' > ')[0].toLowerCase()}/${productSlug}`;
      case 'full-path':
        return `/products/${previewProduct.category?.toLowerCase().replace(/ > /g, '/')}/${productSlug}`;
      default:
        return `/products/${productSlug}`;
    }
  };

  // Generate Product schema
  const generateProductSchema = () => {
    const schema: any = {
      '@context': 'https://schema.org',
      '@type': 'Product',
      name: previewProduct.title,
      description: previewProduct.description,
    };

    if (config.includeOffers) {
      schema.offers = {
        '@type': 'Offer',
        price: previewProduct.price,
        priceCurrency: previewProduct.currency,
      };

      if (config.includeAvailability) {
        schema.offers.availability =
          previewProduct.availability === 'in_stock'
            ? 'https://schema.org/InStock'
            : 'https://schema.org/OutOfStock';
      }
    }

    if (config.includeReviews && previewProduct.rating && previewProduct.reviewCount) {
      schema.aggregateRating = {
        '@type': 'AggregateRating',
        ratingValue: previewProduct.rating,
        reviewCount: previewProduct.reviewCount,
      };
    }

    if (config.includeBrand && previewProduct.brand) {
      schema.brand = {
        '@type': 'Brand',
        name: previewProduct.brand,
      };
    }

    return schema;
  };

  return (
    <BlockStack gap="400">
      {/* Header */}
      <Card>
        <BlockStack gap="300">
          <InlineStack align="space-between" blockAlign="center">
            <div>
              <Text as="h2" variant="headingMd">
                Product SEO Settings
              </Text>
              <Text as="p" variant="bodySm" tone="subdued">
                Configure SEO settings for your product pages
              </Text>
            </div>
            {hasChanges && <Badge tone="warning">Unsaved Changes</Badge>}
          </InlineStack>

          {error && (
            <Banner tone="critical" onDismiss={() => setError(null)}>
              {error}
            </Banner>
          )}

          {success && (
            <Banner tone="success">
              Settings saved successfully!
            </Banner>
          )}
        </BlockStack>
      </Card>

      {/* Preview */}
      <Card>
        <BlockStack gap="400">
          <Text as="h3" variant="headingMd">
            Preview
          </Text>

          {/* SERP Preview */}
          <div
            style={{
              padding: '16px',
              backgroundColor: '#ffffff',
              border: '1px solid #e5e7eb',
              borderRadius: '8px',
            }}
          >
            <BlockStack gap="200">
              <Text as="p" variant="bodySm" tone="subdued">
                {generatePreviewUrl()}
              </Text>
              <Text as="h3" variant="headingLg" fontWeight="semibold">
                <span style={{ color: '#1a0dab' }}>{generatePreviewTitle()}</span>
              </Text>
              {config.showStarRatings && previewProduct.rating && (
                <InlineStack gap="100" blockAlign="center">
                  <InlineStack gap="050">
                    {Array.from({ length: 5 }).map((_, i) => (
                      <Icon
                        key={i}
                        source={StarFilledIcon}
                        tone={i < Math.floor(previewProduct.rating!) ? 'warning' : 'subdued'}
                      />
                    ))}
                  </InlineStack>
                  <Text as="span" variant="bodySm">
                    {previewProduct.rating} ({previewProduct.reviewCount} reviews)
                  </Text>
                </InlineStack>
              )}
              <Text as="p" variant="bodyMd">
                {generatePreviewDescription()}
              </Text>
              {config.includePrice && (
                <InlineStack gap="200" blockAlign="center">
                  <Icon source={MoneyIcon} tone="success" />
                  <Text as="span" variant="bodyMd" fontWeight="semibold">
                    ${previewProduct.price}
                  </Text>
                  {config.showStockAvailability && (
                    <Badge tone={previewProduct.availability === 'in_stock' ? 'success' : 'critical'}>
                      {previewProduct.availability === 'in_stock' ? 'In Stock' : 'Out of Stock'}
                    </Badge>
                  )}
                </InlineStack>
              )}
            </BlockStack>
          </div>
        </BlockStack>
      </Card>

      {/* Settings Tabs */}
      <Card>
        <Tabs tabs={tabs} selected={selectedTab} onSelect={setSelectedTab}>
          <div style={{ marginTop: '16px' }}>
            {/* Meta Tags Tab */}
            {selectedTab === 0 && (
              <BlockStack gap="400">
                <Text as="h3" variant="headingMd">
                  Meta Tag Templates
                </Text>

                <TextField
                  label="Title Template"
                  value={config.titleTemplate}
                  onChange={(value) => updateConfig({ titleTemplate: value })}
                  autoComplete="off"
                  helpText="Available variables: {product_name}, {price}, {brand}, {category}, {store_name}"
                />

                <TextField
                  label="Description Template"
                  value={config.descriptionTemplate}
                  onChange={(value) => updateConfig({ descriptionTemplate: value })}
                  multiline={3}
                  autoComplete="off"
                  helpText="Available variables: {product_description}, {product_name}, {price}, {brand}"
                />

                <Checkbox
                  label="Auto-generate titles for products without custom titles"
                  checked={config.autoGenerateTitles}
                  onChange={(value) => updateConfig({ autoGenerateTitles: value })}
                />

                <Checkbox
                  label="Auto-generate descriptions for products without custom descriptions"
                  checked={config.autoGenerateDescriptions}
                  onChange={(value) => updateConfig({ autoGenerateDescriptions: value })}
                />

                <Checkbox
                  label="Include price in meta description"
                  checked={config.includePrice}
                  onChange={(value) => updateConfig({ includePrice: value })}
                />

                <Checkbox
                  label="Include categories in meta data"
                  checked={config.includeCategories}
                  onChange={(value) => updateConfig({ includeCategories: value })}
                />
              </BlockStack>
            )}

            {/* Schema Markup Tab */}
            {selectedTab === 1 && (
              <BlockStack gap="400">
                <Text as="h3" variant="headingMd">
                  Product Schema Settings
                </Text>

                <Checkbox
                  label="Enable Product schema markup"
                  checked={config.enableProductSchema}
                  onChange={(value) => updateConfig({ enableProductSchema: value })}
                  helpText="Adds structured data to help search engines understand your products"
                />

                {config.enableProductSchema && (
                  <>
                    <Checkbox
                      label="Include review ratings"
                      checked={config.includeReviews}
                      onChange={(value) => updateConfig({ includeReviews: value })}
                      helpText="Shows star ratings in search results"
                    />

                    {config.includeReviews && (
                      <TextField
                        label="Minimum reviews required to show rating"
                        type="number"
                        value={config.minimumReviewsForRating.toString()}
                        onChange={(value) =>
                          updateConfig({ minimumReviewsForRating: parseInt(value, 10) || 1 })
                        }
                        autoComplete="off"
                      />
                    )}

                    <Checkbox
                      label="Include offer information (price, availability)"
                      checked={config.includeOffers}
                      onChange={(value) => updateConfig({ includeOffers: value })}
                    />

                    <Checkbox
                      label="Include brand information"
                      checked={config.includeBrand}
                      onChange={(value) => updateConfig({ includeBrand: value })}
                    />

                    <Checkbox
                      label="Include availability status"
                      checked={config.includeAvailability}
                      onChange={(value) => updateConfig({ includeAvailability: value })}
                    />

                    {/* Schema Preview */}
                    <div>
                      <Text as="p" variant="bodySm" fontWeight="semibold">
                        Schema Preview
                      </Text>
                      <div
                        style={{
                          padding: '16px',
                          backgroundColor: '#1e293b',
                          borderRadius: '8px',
                          fontFamily: 'monospace',
                          fontSize: '12px',
                          color: '#f1f5f9',
                          overflow: 'auto',
                          maxHeight: '400px',
                        }}
                      >
                        <pre>{JSON.stringify(generateProductSchema(), null, 2)}</pre>
                      </div>
                    </div>
                  </>
                )}
              </BlockStack>
            )}

            {/* URLs Tab */}
            {selectedTab === 2 && (
              <BlockStack gap="400">
                <Text as="h3" variant="headingMd">
                  Product URL Settings
                </Text>

                <Select
                  label="URL Structure"
                  options={[
                    { label: 'Simple: /products/product-name', value: 'simple' },
                    { label: 'Category: /products/category/product-name', value: 'category' },
                    { label: 'Full Path: /products/category/subcategory/product-name', value: 'full-path' },
                  ]}
                  value={config.urlStructure}
                  onChange={(value) => updateConfig({ urlStructure: value as 'simple' | 'category' | 'full-path' })}
                />

                <Checkbox
                  label="Remove stop words from URLs"
                  checked={config.removeStopWords}
                  onChange={(value) => updateConfig({ removeStopWords: value })}
                  helpText='Remove words like "a", "the", "and" from product URLs'
                />

                <Checkbox
                  label="Force lowercase URLs"
                  checked={config.lowercaseUrls}
                  onChange={(value) => updateConfig({ lowercaseUrls: value })}
                  helpText="Convert all product URLs to lowercase"
                />

                <div
                  style={{
                    padding: '16px',
                    backgroundColor: '#f0f9ff',
                    border: '1px solid #bae6fd',
                    borderRadius: '8px',
                  }}
                >
                  <Text as="p" variant="bodySm" fontWeight="semibold">
                    Preview URL
                  </Text>
                  <Text as="p" variant="bodySm">
                    {generatePreviewUrl()}
                  </Text>
                </div>
              </BlockStack>
            )}

            {/* Images Tab */}
            {selectedTab === 3 && (
              <BlockStack gap="400">
                <Text as="h3" variant="headingMd">
                  Product Image SEO
                </Text>

                <Checkbox
                  label="Auto-generate alt text for product images"
                  checked={config.autoGenerateAltText}
                  onChange={(value) => updateConfig({ autoGenerateAltText: value })}
                />

                {config.autoGenerateAltText && (
                  <TextField
                    label="Alt Text Template"
                    value={config.altTextTemplate}
                    onChange={(value) => updateConfig({ altTextTemplate: value })}
                    autoComplete="off"
                    helpText="Available variables: {product_name}, {variant}, {color}, {size}"
                  />
                )}

                <Checkbox
                  label="Optimize image file names"
                  checked={config.optimizeImageNames}
                  onChange={(value) => updateConfig({ optimizeImageNames: value })}
                  helpText="Rename image files to include product name and keywords"
                />

                <div
                  style={{
                    padding: '16px',
                    backgroundColor: '#f0f9ff',
                    border: '1px solid #bae6fd',
                    borderRadius: '8px',
                  }}
                >
                  <BlockStack gap="200">
                    <InlineStack gap="200" blockAlign="center">
                      <Icon source={ImageIcon} tone="info" />
                      <Text as="p" variant="bodySm" fontWeight="semibold">
                        Image SEO Tips
                      </Text>
                    </InlineStack>
                    <ul style={{ marginLeft: '20px' }}>
                      <li>
                        <Text as="span" variant="bodySm">
                          Use descriptive, keyword-rich file names
                        </Text>
                      </li>
                      <li>
                        <Text as="span" variant="bodySm">
                          Compress images to reduce file size
                        </Text>
                      </li>
                      <li>
                        <Text as="span" variant="bodySm">
                          Use WebP format for better compression
                        </Text>
                      </li>
                      <li>
                        <Text as="span" variant="bodySm">
                          Add alt text to all product images
                        </Text>
                      </li>
                    </ul>
                  </BlockStack>
                </div>
              </BlockStack>
            )}
          </div>
        </Tabs>
      </Card>

      {/* Inventory Settings */}
      <Card>
        <BlockStack gap="400">
          <Text as="h3" variant="headingMd">
            Inventory & Availability
          </Text>

          <Checkbox
            label="Hide out-of-stock products from search engines"
            checked={config.hideOutOfStock}
            onChange={(value) => updateConfig({ hideOutOfStock: value })}
            helpText="Adds noindex tag to out-of-stock products"
          />

          <Checkbox
            label="Show stock availability in search results"
            checked={config.showStockAvailability}
            onChange={(value) => updateConfig({ showStockAvailability: value })}
          />

          <Checkbox
            label="Show star ratings in search results"
            checked={config.showStarRatings}
            onChange={(value) => updateConfig({ showStarRatings: value })}
          />
        </BlockStack>
      </Card>

      {/* Best Practices */}
      <Card>
        <BlockStack gap="300">
          <Text as="h3" variant="headingSm">
            Product SEO Best Practices
          </Text>
          <div
            style={{
              padding: '16px',
              backgroundColor: '#f0f9ff',
              border: '1px solid #bae6fd',
              borderRadius: '8px',
            }}
          >
            <ul style={{ marginLeft: '20px' }}>
              <li>
                <Text as="span" variant="bodySm">
                  <strong>Unique descriptions</strong> - Write unique descriptions for each product
                </Text>
              </li>
              <li>
                <Text as="span" variant="bodySm">
                  <strong>Include reviews</strong> - Star ratings boost click-through rates
                </Text>
              </li>
              <li>
                <Text as="span" variant="bodySm">
                  <strong>Optimize images</strong> - Use descriptive file names and alt text
                </Text>
              </li>
              <li>
                <Text as="span" variant="bodySm">
                  <strong>Schema markup</strong> - Product schema helps Google understand your products
                </Text>
              </li>
              <li>
                <Text as="span" variant="bodySm">
                  <strong>Clean URLs</strong> - Use simple, keyword-rich URLs
                </Text>
              </li>
              <li>
                <Text as="span" variant="bodySm">
                  <strong>Stock status</strong> - Keep availability info up to date
                </Text>
              </li>
            </ul>
          </div>
        </BlockStack>
      </Card>

      {/* Save Button */}
      <InlineStack align="end">
        <Button variant="primary" onClick={handleSave} disabled={!hasChanges} loading={isSaving}>
          Save Settings
        </Button>
      </InlineStack>
    </BlockStack>
  );
}
